version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_gym
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=gymDatabase
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    command: mongod --auth
    restart: unless-stopped
    networks:
      - gym-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express_gym
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - gym-network

volumes:
  mongodb_data:
    driver: local

networks:
  gym-network:
    driver: bridge
