version: '3.8'

services:
  db:
    container_name: mariadb
    restart: always
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: "SchoolDB"
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "qwerty"
    ports:
      - "3306:3306"
    volumes:
      - mariadb-volume:/var/lib/mysql

volumes:
  mariadb-volume:

